apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-deployment
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - name: wordpress-image
        image: wordpress:4.8-apache
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env: #variáveis de ambiente que serão necessárias
          - name: WORDPRESS_DB_HOST
            value: mysql-service #qual o host do nosso banco de dados dentro do kubernetes? Esse valor será dado pelo service. Dentro do kubernetes, cada deployment que possui a sua service, a comunicação entre os pods é feita através do nome do hosts. Esse nome vem la do service.
          - name: WORDPRESS_DB_PASSWORD
            #value: wordpress-2020
            valueFrom: #após configuração da secret no arquivo de configurações, vamos utilizar o valueFrom para acessá-las
                secretKeyRef:
                  name: mysql-secret
                  key: password
        volumeMounts: #configurando os volumes que foram definidos em configuracoes
          - name: wordpress-volume
            mountPath: /var/www/html #onde que é gravado a informação
      volumes: #criando uma spec de volume - no mesmo nível que containers
        - name: wordpress-volume #mesmo nome do volumeMounts
          persistentVolumeClaim:
              claimName: wordpress-pvc #pegar o mesmo nome que foi definido em configuracoes